language: ruby
rvm:
- 2.1

script:
  - bundle exec coffeelint.rb */app.coffee

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
